/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      "colors": {
              "tri-saffron": "#FF9933",
              "tri-green": "#138808",
              "on-tertiary-fixed-variant": "#474744",
              "primary-fixed-dim": "#b7ccb9",
              "surface-container-lowest": "#ffffff",
              "inverse-surface": "#303030",
              "on-tertiary-container": "#aeada9",
              "soft-olive": "#74826B",
              "surface-variant": "#e4e2e1",
              "surface-tint": "#506354",
              "tertiary-fixed-dim": "#c8c6c2",
              "tertiary": "#2b2b28",
              "tertiary-fixed": "#e4e2de",
              "outline": "#737872",
              "surface-bright": "#fcf9f8",
              "on-secondary": "#ffffff",
              "on-primary": "#ffffff",
              "surface-container-low": "#f6f3f2",
              "surface-container-highest": "#e4e2e1",
              "primary-fixed": "#d3e8d4",
              "on-tertiary-fixed": "#1b1c19",
              "secondary-fixed": "#fdddba",
              "tertiary-container": "#41413e",
              "on-primary-container": "#9eb2a0",
              "on-error-container": "#93000a",
              "earth-accent": "#8C7355",
              "outline-variant": "#c3c8c1",
              "inverse-primary": "#b7ccb9",
              "on-primary-fixed-variant": "#394b3d",
              "inverse-on-surface": "#f3f0ef",
              "on-surface": "#1b1c1b",
              "charcoal-text": "#2C2C2C",
              "surface-container-high": "#eae7e7",
              "secondary-fixed-dim": "#e0c19f",
              "on-primary-fixed": "#0e1f13",
              "primary-container": "#334537",
              "on-surface-variant": "#434843",
              "on-background": "#1b1c1b",
              "on-secondary-fixed": "#281803",
              "secondary-container": "#fadab7",
              "surface-dim": "#dcd9d8",
              "on-secondary-container": "#765f42",
              "secondary": "#715a3e",
              "sage-primary": "#4A5D4E",
              "on-error": "#ffffff",
              "error-container": "#ffdad6",
              "on-secondary-fixed-variant": "#584329",
              "surface-container": "#f0edec",
              "stone-bg": "#F5F2ED",
              "on-tertiary": "#ffffff",
              "surface": "#fcf9f8",
              "background": "#fcf9f8",
              "primary": "#1d2f22",
              "error": "#ba1a1a"
      },
      "spacing": {
              "margin-desktop": "80px",
              "margin-mobile": "24px",
              "section-gap": "48px",
              "gutter": "24px",
              "touch-target": "88px"
      }
    },
  },
  plugins: [],
}

